id: select_framework
learningObjectives:
  - Select framework to play on Wilco
hints: []

# hack to skip the framework selection (since we only have Python), and add the files before we create the user's repo
startFlow:
  do:
    - actionId: update_user_props
      params:
        field: "frameworks.backend"
        value: "python"
    - actionId: github_commit_file
      params:
        file: "${tokenizer.ipynb}"
    - actionId: github_commit_file
      params:
        file: "${word_prediction.ipynb}"
    - actionId: github_commit_file
      params:
        file: "${question_answering.ipynb}"
    - actionId: update_user_props
      params:
        field: "nickname"
        value: "Orielly User"
    - actionId: finish_step

# should not get there
trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    do:
      - actionId: finish_step
